services:
  postgres:
    container_name: postgres
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - invilensData1:/var/lib/postgres/data
    ports:
      - 5433:5432

  mongo:
    container_name: mongo
    image: mongo
    ports:
      - 27018:27017
    volumes:
      - invilensMongodb:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=adnan
      - MONGO_INITDB_ROOT_PASSWORD=adnan


  kafka:
    container_name: kafka
    image: apache/kafka
    ports:
      - "9092:9092"

#  config-server:
#    build:
#      context: ./config-server
#    image: config-server
#    container_name: config-server
#    ports:
#      - 8888:8888
#    healthcheck:
#      test: [ "CMD", "curl", "-f", "http://localhost:8888/actuator/health" ]
#      interval: 10s
#      timeout: 5s
#      retries: 5
#      start_period: 15s
#
#  discovery-server:
#    build:
#      context: ./discovery-server
#    container_name: discovery-server
#    image: discovery-server
#    environment:
#      - EUREKA_INSTANCE_HOSTNAME=discovery-server-1
#      - CONFIG_SERVER_URL=http://config-server:8888
#    ports:
#      - "8761:8761"
#    depends_on:
#      config-server:
#        condition: service_healthy

  keycloak:
    image: quay.io/keycloak/keycloak:26.4.7
    container_name: keycloak
    command: start-dev
    ports:
      - "8080:8080"
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin

volumes:
  invilensData1:
    driver: local
  invilensMongodb:
    driver: local